name: base
channels:
  - conda-forge
dependencies:
  - opencv-python-headless
  - pytorch
  - scikit-image
  - torchvision
  - tqdm=4.66.1
  - ultralytics
  - pip:
      - colorcorrectionML



